//
//  Unit tests for sdr_rcv.c.
//
#include "test_sdr.h"

#define NAVDATA_FILE ".pocket_navdata.csv"
#define TRACE_FILE   "pocket_sdr.trace"
#define TMP_LOG1     "tmp_test_rcv_log1.log"
#define TMP_LOG2     "tmp_test_rcv_log2.log"
#define TMP_NMEA     "tmp_test_rcv_nmea.nmea"
#define IF_FILE      "test_sdr_rcv_if.bin"

extern double sdr_epoch;
extern double sdr_t_acq;
extern double sdr_t_acq_ext;
extern double sdr_t_coh;
extern double sdr_thres_cn0_ext;
extern double sdr_max_acq;
extern double sdr_thres_cn0_l;
extern int sdr_bump_jump;

static const int EMPTY_TYPES[SDR_MAX_STR] = {0};
static const char *EMPTY_PATHS[SDR_MAX_STR] = {"", "", "", "", "", "", "", ""};

// test file contains a string -------------------------------------------------
static int file_contains(const char *file, const char *str)
{
    FILE *fp = fopen(file, "rb");
    char buff[4096] = "";

    if (!fp) return 0;
    size_t n = fread(buff, 1, sizeof(buff) - 1, fp);
    buff[n] = '\0';
    fclose(fp);
    return strstr(buff, str) != NULL;
}

// remove files generated by these tests ---------------------------------------
static void cleanup_files(void)
{
    remove(NAVDATA_FILE);
    remove(TRACE_FILE);
    remove(IF_FILE);
}

// create zero-filled test IF file --------------------------------------------
static void write_if_file(int ncyc)
{
    uint8_t raw[4000] = {0};
    FILE *fp = fopen(IF_FILE, "wb");
    TEST_ASSERT_TRUE(fp != NULL);
    for (int i = 0; i < ncyc; i++) {
        TEST_ASSERT_EQ_INT(sizeof(raw), fwrite(raw, 1, sizeof(raw), fp));
    }
    fclose(fp);
}

// wait for receiver thread to reach EOF --------------------------------------
static int wait_rcv_end(sdr_rcv_t *rcv, uint32_t timeout)
{
    uint32_t tick = sdr_get_tick();
    while (rcv->state && sdr_get_tick() - tick < timeout) {
        sdr_sleep_msec(1);
    }
    return !rcv->state;
}

// create receiver without tracking channels -----------------------------------
static sdr_rcv_t *new_rcv_empty(int fmt, double fs, const char *opt)
{
    double fo[SDR_MAX_RFCH] = {0};
    int IQ[SDR_MAX_RFCH] = {2, 2, 2, 2, 2, 2, 2, 2};
    int bits[SDR_MAX_RFCH] = {8, 8, 8, 8, 8, 8, 8, 8};
    
    cleanup_files();
    return sdr_rcv_new(NULL, NULL, 0, fmt, fs, fo, IQ, bits, opt);
}

// create receiver with array channels -----------------------------------------
static sdr_rcv_t *new_rcv_array(void)
{
    double fo[SDR_MAX_RFCH] = {
        1575.42e6, 1575.42e6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
    };
    int IQ[SDR_MAX_RFCH] = {2, 2, 2, 2, 2, 2, 2, 2};
    int bits[SDR_MAX_RFCH] = {4, 4, 4, 4, 4, 4, 4, 4};
    
    cleanup_files();
    return sdr_rcv_new(NULL, NULL, 0, SDR_FMT_RAW8, 4e6, fo, IQ, bits,
        "-ARCH=1");
}

// create receiver with one tracking channel -----------------------------------
static sdr_rcv_t *new_rcv_one_channel(void)
{
    const char *sigs[] = {"L1CA"};
    int prns[] = {1};
    double fo[SDR_MAX_RFCH] = {0};
    int IQ[SDR_MAX_RFCH] = {2, 2, 2, 2, 2, 2, 2, 2};
    int bits[SDR_MAX_RFCH] = {8, 8, 8, 8, 8, 8, 8, 8};
    
    cleanup_files();
    return sdr_rcv_new(sigs, prns, 1, SDR_FMT_INT8, 4e6, fo, IQ, bits,
        "-FAST_SRCH");
}

// test sdr_rcv_new() and sdr_rcv_free() ---------------------------------------
static void test_sdr_rcv_new_free_api(void)
{
    sdr_rcv_t *rcv = new_rcv_empty(SDR_FMT_INT8, 4e6, "");
    
    TEST_ASSERT_TRUE(rcv != NULL);
    TEST_ASSERT_EQ_INT(0, rcv->state);
    TEST_ASSERT_EQ_INT(SDR_FMT_INT8, rcv->fmt);
    TEST_ASSERT_NEAR(4e6, rcv->fs, 1e-9);
    TEST_ASSERT_EQ_INT(4000, rcv->N);
    TEST_ASSERT_EQ_INT(1, rcv->nrfch);
    TEST_ASSERT_EQ_INT(0, rcv->nch);
    TEST_ASSERT_EQ_INT(0, rcv->narch);
    TEST_ASSERT_TRUE(rcv->buff[0] != NULL);
    TEST_ASSERT_EQ_INT(2, rcv->buff[0]->IQ);
    sdr_rcv_free(rcv);
    sdr_rcv_free(NULL);
    
    rcv = new_rcv_one_channel();
    TEST_ASSERT_TRUE(rcv != NULL);
    TEST_ASSERT_EQ_INT(1, rcv->nch);
    TEST_ASSERT_TRUE(rcv->th[0] != NULL);
    TEST_ASSERT_TRUE(rcv->th[0]->ch != NULL);
    TEST_ASSERT_EQ_INT(1, rcv->th[0]->ch->no);
    TEST_ASSERT_EQ_INT(1, rcv->fast_acq);
    sdr_rcv_free(rcv);
    cleanup_files();
}

// test sdr_rcv_new() array configuration --------------------------------------
static void test_sdr_rcv_new_array_api(void)
{
    sdr_rcv_t *rcv = new_rcv_array();
    
    TEST_ASSERT_TRUE(rcv != NULL);
    TEST_ASSERT_EQ_INT(SDR_FMT_RAW8, rcv->fmt);
    TEST_ASSERT_EQ_INT(2, rcv->nrfch);
    TEST_ASSERT_EQ_INT(1, rcv->narch);
    TEST_ASSERT_TRUE(rcv->array != NULL);
    TEST_ASSERT_TRUE(rcv->buff[0] != NULL);
    TEST_ASSERT_TRUE(rcv->buff[1] != NULL);
    TEST_ASSERT_TRUE(rcv->buff[2] != NULL);
    TEST_ASSERT_NEAR(0.5, rcv->arch[0].scale, 1e-12);
    
    sdr_rcv_free(rcv);
    cleanup_files();
}

// test sdr_rcv_start() and sdr_rcv_stop() -------------------------------------
static void test_sdr_rcv_start_stop_api(void)
{
    sdr_rcv_t *rcv = new_rcv_empty(SDR_FMT_INT8, 4e6, "-SCALE=1.5");
    sdr_dev_t *dev = sdr_dev_open(-1, -1);
    char buff[256];
    
    TEST_ASSERT_EQ_INT(0, sdr_rcv_start(NULL, SDR_DEV_USB, dev, EMPTY_TYPES,
        EMPTY_PATHS));
    TEST_ASSERT_EQ_INT(1, sdr_rcv_start(rcv, SDR_DEV_USB, dev, EMPTY_TYPES,
        EMPTY_PATHS));
    TEST_ASSERT_EQ_INT(1, rcv->state);
    TEST_ASSERT_EQ_INT(SDR_DEV_USB, rcv->dev);
    TEST_ASSERT_TRUE(rcv->pvt != NULL);
    TEST_ASSERT_TRUE(rcv->rfch[0].LUT != NULL);
    TEST_ASSERT_EQ_INT(0, sdr_rcv_start(rcv, SDR_DEV_USB, dev, EMPTY_TYPES,
        EMPTY_PATHS));
    
    TEST_ASSERT_TRUE(sdr_rcv_rcv_stat(rcv, buff, sizeof(buff)) > 0);
    TEST_ASSERT_TRUE(strstr(buff, "PocketSDR_FE") != NULL);
    TEST_ASSERT_TRUE(strstr(buff, "INT8/1/0") != NULL);
    TEST_ASSERT_TRUE(sdr_rcv_ch_stat(rcv, "", -1, 0.0, 0, 0, buff,
        sizeof(buff)) > 0);
    
    sdr_rcv_stop(rcv);
    TEST_ASSERT_EQ_INT(0, rcv->state);
    TEST_ASSERT_TRUE(rcv->rfch[0].LUT == NULL);
    sdr_rcv_free(rcv);
    sdr_dev_close(dev);
    cleanup_files();
}

// test sdr_rcv_open_*() and sdr_rcv_close() -----------------------------------
static void test_sdr_rcv_open_close_api(void)
{
    sdr_rcv_t *rcv;
    int prns[] = {1};
    const char *sigs[] = {"L1CA"};
    double fo[SDR_MAX_RFCH] = {0};
    int IQ[SDR_MAX_RFCH] = {2, 2, 2, 2, 2, 2, 2, 2};
    int bits[SDR_MAX_RFCH] = {8, 8, 8, 8, 8, 8, 8, 8};
    
    rcv = sdr_rcv_open_dev(NULL, NULL, 0, -1, -1, "", EMPTY_TYPES, EMPTY_PATHS,
        "");
    TEST_ASSERT_TRUE(rcv != NULL);
    TEST_ASSERT_EQ_INT(SDR_DEV_USB, rcv->dev);
    TEST_ASSERT_EQ_INT(SDR_FMT_RAW8, rcv->fmt);
    TEST_ASSERT_EQ_INT(2, rcv->nrfch);
    sdr_rcv_close(rcv);
    cleanup_files();
    
    rcv = sdr_rcv_open_sdev(NULL, NULL, 0, "stub", SDR_FMT_CS8, 4e6,
        1575.42e6, EMPTY_TYPES, EMPTY_PATHS, "-GAIN=10 -BW=2");
    TEST_ASSERT_TRUE(rcv != NULL);
    TEST_ASSERT_EQ_INT(SDR_DEV_SOAPY, rcv->dev);
    TEST_ASSERT_EQ_INT(SDR_FMT_CS8, rcv->fmt);
    sdr_rcv_close(rcv);
    cleanup_files();
    
    TEST_ASSERT_TRUE(sdr_rcv_open_sdev(NULL, NULL, 0, "stub", SDR_FMT_RAW8,
        4e6, 1575.42e6, EMPTY_TYPES, EMPTY_PATHS, "") == NULL);
    TEST_ASSERT_TRUE(sdr_rcv_open_file(sigs, prns, 1, SDR_FMT_INT8, 4e6, fo,
        IQ, bits, 0.0, 1.0, "no_such_sdr_rcv_file.bin", EMPTY_TYPES,
        EMPTY_PATHS, "") == NULL);
    sdr_rcv_close(NULL);
    cleanup_files();
}

// test multiple output streams with selectable types --------------------------
static void test_sdr_rcv_multi_str_api(void)
{
    sdr_rcv_t *rcv = new_rcv_empty(SDR_FMT_INT8, 4e6, "");
    sdr_dev_t *dev = sdr_dev_open(-1, -1);
    int types[SDR_MAX_STR] = {
        SDR_STR_LOG, SDR_STR_NMEA, SDR_STR_LOG, 0, 0, 0, 0, 0
    };
    const char *paths[SDR_MAX_STR] = {
        TMP_LOG1, TMP_NMEA, TMP_LOG2, "", "", "", "", ""
    };
    int stat[SDR_MAX_STR] = {0};
    uint8_t data[] = "$GNRMC,TEST";
    
    remove(TMP_LOG1);
    remove(TMP_LOG2);
    remove(TMP_NMEA);
    TEST_ASSERT_EQ_INT(1, sdr_rcv_start(rcv, SDR_DEV_USB, dev, types, paths));
    TEST_ASSERT_EQ_INT(SDR_STR_LOG, rcv->str_type[0]);
    TEST_ASSERT_EQ_INT(SDR_STR_NMEA, rcv->str_type[1]);
    TEST_ASSERT_EQ_INT(SDR_STR_LOG, rcv->str_type[2]);
    TEST_ASSERT_EQ_INT(SDR_STR_NONE, rcv->str_type[3]);
    sdr_rcv_str_stat(rcv, stat);
    TEST_ASSERT_TRUE(stat[0] > 0);
    TEST_ASSERT_TRUE(stat[1] > 0);
    TEST_ASSERT_TRUE(stat[2] > 0);
    TEST_ASSERT_EQ_INT(0, stat[3]);
    TEST_ASSERT_EQ_INT((int)sizeof(data), sdr_rcv_write_str(rcv, SDR_STR_NMEA,
        data, (int)sizeof(data)));
    TEST_ASSERT_EQ_INT(0, sdr_rcv_write_str(rcv, SDR_STR_RTCM3, data,
        (int)sizeof(data)));
    sdr_rcv_stop(rcv);
    TEST_ASSERT_TRUE(rcv->strs[0] == NULL);
    TEST_ASSERT_EQ_INT(SDR_STR_NONE, rcv->str_type[0]);
    
    // both log streams contain START and STOP records
    TEST_ASSERT_TRUE(file_contains(TMP_LOG1, "START"));
    TEST_ASSERT_TRUE(file_contains(TMP_LOG1, "STOP"));
    TEST_ASSERT_TRUE(file_contains(TMP_LOG2, "START"));
    TEST_ASSERT_TRUE(file_contains(TMP_LOG2, "STOP"));
    TEST_ASSERT_TRUE(file_contains(TMP_NMEA, "$GNRMC,TEST"));
    
    sdr_rcv_free(rcv);
    sdr_dev_close(dev);
    remove(TMP_LOG1);
    remove(TMP_LOG2);
    remove(TMP_NMEA);
    cleanup_files();
}

// test output stream open error -----------------------------------------------
static void test_sdr_rcv_str_error_api(void)
{
    sdr_rcv_t *rcv = new_rcv_empty(SDR_FMT_INT8, 4e6, "");
    sdr_dev_t *dev = sdr_dev_open(-1, -1);
    int types[SDR_MAX_STR] = {
        SDR_STR_NMEA, SDR_STR_LOG, 0, 0, 0, 0, 0, 0
    };
    // a directory cannot be opened as a file (a missing one would be created)
    const char *paths[SDR_MAX_STR] = {
        ".", TMP_LOG1, "", "", "", "", "", ""
    };
    int stat[SDR_MAX_STR] = {0};
    uint8_t data[] = "$GNRMC,TEST";
    
    remove(TMP_LOG1);
    TEST_ASSERT_EQ_INT(1, sdr_rcv_start(rcv, SDR_DEV_USB, dev, types, paths));
    
    // the type is kept without a stream to report the open error
    TEST_ASSERT_TRUE(rcv->strs[0] == NULL);
    TEST_ASSERT_EQ_INT(SDR_STR_NMEA, rcv->str_type[0]);
    sdr_rcv_str_stat(rcv, stat);
    TEST_ASSERT_EQ_INT(-1, stat[0]);
    TEST_ASSERT_TRUE(stat[1] > 0);
    TEST_ASSERT_EQ_INT(0, stat[2]);
    
    // a stream failed to open is not written to
    TEST_ASSERT_EQ_INT(0, sdr_rcv_write_str(rcv, SDR_STR_NMEA, data,
        (int)sizeof(data)));
    sdr_rcv_stop(rcv);
    TEST_ASSERT_EQ_INT(SDR_STR_NONE, rcv->str_type[0]);
    
    sdr_rcv_free(rcv);
    sdr_dev_close(dev);
    remove(TMP_LOG1);
    cleanup_files();
}

// test offline initial acquisition and EOF drain -----------------------------
static void test_sdr_rcv_offline_eof_drain(void)
{
    const char *sigs[] = {"L1CA", "L1CA"};
    int prns[] = {1, 2};
    double fo[SDR_MAX_RFCH] = {0}, t_acq0 = sdr_t_acq;
    int IQ[SDR_MAX_RFCH] = {2, 2, 2, 2, 2, 2, 2, 2};
    int bits[SDR_MAX_RFCH] = {8, 8, 8, 8, 8, 8, 8, 8};

    write_if_file(5);
    sdr_t_acq = 0.020;
    sdr_rcv_t *rcv = sdr_rcv_open_file(sigs, prns, 2, SDR_FMT_INT8, 4e6,
        fo, IQ, bits, 0.0, 1000.0, IF_FILE, EMPTY_TYPES, EMPTY_PATHS,
        "-OFFLINE -FAST_SRCH");
    TEST_ASSERT_TRUE(rcv != NULL);
    TEST_ASSERT_TRUE(wait_rcv_end(rcv, 10000));
    TEST_ASSERT_EQ_INT(1, rcv->offline);
    TEST_ASSERT_EQ_INT(0, rcv->fast_acq);
    TEST_ASSERT_EQ_INT(1, rcv->offline_eof);
    TEST_ASSERT_EQ_INT(4, rcv->offline_final_ix);
    for (int i = 0; i < 2; i++) {
        TEST_ASSERT_EQ_INT(1, rcv->th[i]->initial_acq);
        TEST_ASSERT_EQ_INT(1, rcv->th[i]->drained);
        TEST_ASSERT_EQ_INT(3, rcv->th[i]->ix);
        TEST_ASSERT_EQ_INT(SDR_STATE_IDLE, rcv->th[i]->ch->state);
        TEST_ASSERT_TRUE(rcv->th[i]->ch->acq->P_sum == NULL);
        TEST_ASSERT_EQ_INT(0, rcv->th[i]->ch->acq->n_sum);
    }
    sdr_rcv_close(rcv);
    sdr_t_acq = t_acq0;
    cleanup_files();
}

// test offline failed acquisition is not scheduled again ---------------------
static void test_sdr_rcv_offline_initial_failure(void)
{
    const char *sigs[] = {"L1CA"};
    int prns[] = {1};
    double fo[SDR_MAX_RFCH] = {0}, t_acq0 = sdr_t_acq;
    double thres0 = sdr_thres_cn0_l;
    int IQ[SDR_MAX_RFCH] = {2, 2, 2, 2, 2, 2, 2, 2};
    int bits[SDR_MAX_RFCH] = {8, 8, 8, 8, 8, 8, 8, 8};

    write_if_file(12);
    sdr_t_acq = 0.003;
    sdr_thres_cn0_l = 1000.0;
    sdr_rcv_t *rcv = sdr_rcv_open_file(sigs, prns, 1, SDR_FMT_INT8, 4e6,
        fo, IQ, bits, 0.0, 0.001, IF_FILE, EMPTY_TYPES, EMPTY_PATHS,
        "-OFFLINE");
    TEST_ASSERT_TRUE(rcv != NULL);
    TEST_ASSERT_TRUE(wait_rcv_end(rcv, 10000));
    TEST_ASSERT_EQ_INT(1, rcv->th[0]->initial_acq);
    TEST_ASSERT_EQ_INT(0, rcv->th[0]->reacq);
    TEST_ASSERT_EQ_INT(10, rcv->th[0]->ix);
    TEST_ASSERT_EQ_INT(SDR_STATE_IDLE, rcv->th[0]->ch->state);
    TEST_ASSERT_TRUE(rcv->th[0]->ch->acq->P_sum == NULL);
    sdr_rcv_close(rcv);
    sdr_t_acq = t_acq0;
    sdr_thres_cn0_l = thres0;
    cleanup_files();
}

// test offline EOF drain with no channels ------------------------------------
static void test_sdr_rcv_offline_no_channels(void)
{
    double fo[SDR_MAX_RFCH] = {0};
    int IQ[SDR_MAX_RFCH] = {2, 2, 2, 2, 2, 2, 2, 2};
    int bits[SDR_MAX_RFCH] = {8, 8, 8, 8, 8, 8, 8, 8};

    write_if_file(100);
    sdr_rcv_t *rcv = sdr_rcv_open_file(NULL, NULL, 0, SDR_FMT_INT8, 4e6,
        fo, IQ, bits, 0.0, 0.0, IF_FILE, EMPTY_TYPES, EMPTY_PATHS, "-OFFLINE");
    TEST_ASSERT_TRUE(rcv != NULL);
    TEST_ASSERT_TRUE(wait_rcv_end(rcv, 2000));
    TEST_ASSERT_EQ_INT(1, rcv->offline_eof);
    TEST_ASSERT_EQ_INT(99, rcv->offline_final_ix);
    sdr_rcv_close(rcv);
    cleanup_files();
}

// test sdr_rcv_setopt() -------------------------------------------------------
static void test_sdr_rcv_setopt_api(void)
{
    double epoch0 = sdr_epoch;
    double t_acq0 = sdr_t_acq, t_acq_ext0 = sdr_t_acq_ext;
    double t_coh0 = sdr_t_coh, thres_cn0_ext0 = sdr_thres_cn0_ext;
    double max_acq0 = sdr_max_acq;
    int bump_jump0 = sdr_bump_jump;
    
    sdr_rcv_setopt("epoch", 0.2);
    sdr_rcv_setopt("t_acq", 0.04);
    sdr_rcv_setopt("t_acq_ext", 0.12);
    sdr_rcv_setopt("t_coh", 0.03);
    sdr_rcv_setopt("thres_cn0_ext", 29.0);
    sdr_rcv_setopt("max_acq", 7.0);
    sdr_rcv_setopt("bump_jump", 1.0);
    TEST_ASSERT_NEAR(0.2, sdr_epoch, 1e-12);
    TEST_ASSERT_NEAR(0.04, sdr_t_acq, 1e-12);
    TEST_ASSERT_NEAR(0.12, sdr_t_acq_ext, 1e-12);
    TEST_ASSERT_NEAR(0.03, sdr_t_coh, 1e-12);
    TEST_ASSERT_NEAR(29.0, sdr_thres_cn0_ext, 1e-12);
    TEST_ASSERT_NEAR(7.0, sdr_max_acq, 1e-12);
    TEST_ASSERT_EQ_INT(1, sdr_bump_jump);
    
    sdr_rcv_setopt("unknown_option", 123.0);
    sdr_rcv_setopt("epoch", epoch0);
    sdr_rcv_setopt("t_acq", t_acq0);
    sdr_rcv_setopt("t_acq_ext", t_acq_ext0);
    sdr_rcv_setopt("t_coh", t_coh0);
    sdr_rcv_setopt("thres_cn0_ext", thres_cn0_ext0);
    sdr_rcv_setopt("max_acq", max_acq0);
    sdr_rcv_setopt("bump_jump", bump_jump0);
}

// test receiver status APIs ---------------------------------------------------
static void test_sdr_rcv_status_api(void)
{
    sdr_rcv_t *rcv = new_rcv_one_channel();
    char buff[2048];
    int stat[SDR_MAX_STR] = {-1, -1, -1, -1, -1, -1, -1, -1};
    double cstat[16], pos[16], rfstat[8], corr_P[32], I[32];
    sdr_cpx_t C[32], hist_P[32];
    
    TEST_ASSERT_TRUE(sdr_rcv_rcv_stat(NULL, buff, sizeof(buff)) > 0);
    TEST_ASSERT_TRUE(strstr(buff, "--- ---/-/-") != NULL);
    TEST_ASSERT_TRUE(sdr_rcv_rcv_stat(rcv, buff, sizeof(buff)) > 0);
    TEST_ASSERT_TRUE(strstr(buff, "--- ---/-/-") != NULL);
    
    sdr_rcv_str_stat(NULL, stat);
    TEST_ASSERT_EQ_INT(0, stat[0]);
    TEST_ASSERT_EQ_INT(0, stat[1]);
    TEST_ASSERT_EQ_INT(0, stat[3]);
    TEST_ASSERT_EQ_INT(0, stat[SDR_MAX_STR-1]);
    
    TEST_ASSERT_EQ_INT(0, sdr_rcv_sat_stat(NULL, "G01", buff, sizeof(buff)));
    TEST_ASSERT_EQ_INT(0, sdr_rcv_sat_stat(rcv, "???", buff, sizeof(buff)));
    TEST_ASSERT_TRUE(sdr_rcv_ch_stat(NULL, "G", -1, 0.0, 0, 0, buff,
        sizeof(buff)) > 0);
    sdr_rcv_sel_ch(NULL, 1, 0.1);
    sdr_rcv_sel_ch(rcv, 1, 0.1);
    TEST_ASSERT_EQ_INT(0, sdr_rcv_corr_stat(NULL, 1, cstat, pos, C, corr_P,
        I));
    TEST_ASSERT_EQ_INT(0, sdr_rcv_corr_stat(rcv, 0, cstat, pos, C, corr_P, I));
    TEST_ASSERT_EQ_INT(0, sdr_rcv_corr_hist(rcv, 1, 1.0, cstat, hist_P));
    TEST_ASSERT_EQ_INT(0, sdr_rcv_rfch_stat(rcv, 1, rfstat));
    TEST_ASSERT_EQ_INT(0, sdr_rcv_pvt_sol(rcv, buff, sizeof(buff)));
    
    sdr_rcv_free(rcv);
    cleanup_files();
}

// test RF channel data APIs ---------------------------------------------------
static void test_sdr_rcv_rfch_data_api(void)
{
    sdr_rcv_t *rcv = new_rcv_empty(SDR_FMT_INT8, 1000.0, "");
    double stat[8], hist1[256], hist2[256];
    float psd[16];
    int val[256];
    
    for (int i = 0; i < rcv->buff[0]->N; i++) {
        rcv->buff[0]->data[i] = SDR_CPX8((int8_t)(i % 5 - 2),
            (int8_t)(2 - i % 5));
    }
    rcv->state = 1;
    rcv->dev = SDR_DEV_FILE;
    rcv->ix = 20;
    rcv->stats.std = 1.25;
    
    TEST_ASSERT_EQ_INT(1, sdr_rcv_rfch_stat(rcv, 1, stat));
    TEST_ASSERT_NEAR(SDR_DEV_FILE, stat[0], 1e-12);
    TEST_ASSERT_NEAR(SDR_FMT_INT8, stat[1], 1e-12);
    TEST_ASSERT_NEAR(1000.0, stat[2], 1e-12);
    TEST_ASSERT_NEAR(1.25, stat[6], 1e-12);
    TEST_ASSERT_EQ_INT(0, sdr_rcv_rfch_stat(rcv, 2, stat));
    TEST_ASSERT_EQ_INT(16, sdr_rcv_rfch_psd(rcv, 1, 0.016, 16, psd));
    TEST_ASSERT_TRUE(sdr_rcv_rfch_hist(rcv, 1, 0.010, val, hist1, hist2) > 0);
    TEST_ASSERT_EQ_INT(0, sdr_rcv_rfch_psd(rcv, 1, 0.001, 16, psd));
    
    rcv->state = 0;
    sdr_rcv_free(rcv);
    cleanup_files();
}

// test receiver gain and filter APIs ------------------------------------------
static void test_sdr_rcv_gain_filt_api(void)
{
    sdr_rcv_t *rcv = new_rcv_empty(SDR_FMT_INT8, 4e6, "");
    sdr_dev_t *dev = sdr_dev_open(-1, -1);
    char buff[256];
    double bw = 0.0, freq = 0.0;
    int order = 0;
    
    TEST_ASSERT_EQ_INT(-1, sdr_rcv_get_gain(NULL, 0));
    TEST_ASSERT_EQ_INT(0, sdr_rcv_set_gain(rcv, 0, 10));
    TEST_ASSERT_EQ_INT(0, sdr_rcv_get_filt(rcv, 0, &bw, &freq, &order));
    
    TEST_ASSERT_EQ_INT(1, sdr_rcv_start(rcv, SDR_DEV_USB, dev, EMPTY_TYPES,
        EMPTY_PATHS));
    TEST_ASSERT_EQ_INT(1, sdr_rcv_pvt_sol(rcv, buff, sizeof(buff)));
    TEST_ASSERT_TRUE(sdr_rcv_sat_stat(rcv, "G01", buff, sizeof(buff)) > 0);
    TEST_ASSERT_EQ_INT(1, sdr_rcv_set_gain(rcv, 0, 12));
    TEST_ASSERT_EQ_INT(12, sdr_rcv_get_gain(rcv, 0));
    TEST_ASSERT_EQ_INT(1, sdr_rcv_set_filt(rcv, 0, 2.5e6, 1.0e6, 3));
    TEST_ASSERT_EQ_INT(1, sdr_rcv_get_filt(rcv, 0, &bw, &freq, &order));
    TEST_ASSERT_NEAR(2.5e6, bw, 1e-9);
    TEST_ASSERT_NEAR(1.0e6, freq, 1e-9);
    TEST_ASSERT_EQ_INT(3, order);
    
    sdr_rcv_stop(rcv);
    sdr_rcv_free(rcv);
    sdr_dev_close(dev);
    cleanup_files();
}

// test receiver array APIs ----------------------------------------------------
static void test_sdr_rcv_array_api(void)
{
    sdr_rcv_t *rcv = new_rcv_array();
    sdr_rcv_t *rcv_no_array = new_rcv_empty(SDR_FMT_INT8, 4e6, "");
    double ant_pos[SDR_MAX_RFCH * 3] = {0};
    int ant_ena[SDR_MAX_RFCH] = {1, 1};
    double az = 0.0, el = 0.0, rpy[3], bias[SDR_MAX_RFCH], rms;
    int nep;
    
    ant_pos[3] = 0.10;
    TEST_ASSERT_EQ_INT(0, sdr_rcv_array_ant_pos(NULL, ant_pos, ant_ena));
    TEST_ASSERT_EQ_INT(0, sdr_rcv_array_ant_pos(rcv_no_array, ant_pos,
        ant_ena));
    TEST_ASSERT_EQ_INT(1, sdr_rcv_array_ant_pos(rcv, ant_pos, ant_ena));
    TEST_ASSERT_NEAR(0.10, rcv->array->ant_pos[1][0], 1e-12);
    
    TEST_ASSERT_EQ_INT(1, sdr_rcv_array_run(rcv, 1));
    TEST_ASSERT_EQ_INT(1, rcv->array->calib_run);
    TEST_ASSERT_EQ_INT(1, sdr_rcv_array_set_mode(rcv, SDR_CALIB_BIAS));
    TEST_ASSERT_EQ_INT(SDR_CALIB_BIAS, rcv->array->calib_mode);
    TEST_ASSERT_EQ_INT(0, sdr_rcv_array_set_mode(rcv, 99));
    TEST_ASSERT_EQ_INT(1, sdr_rcv_array_stat(rcv, rpy, bias, &rms, &nep));
    TEST_ASSERT_EQ_INT(0, nep);
    
    TEST_ASSERT_EQ_INT(1, sdr_rcv_array_set_beam(rcv, rcv->nrfch, 0.25, 0.75));
    TEST_ASSERT_EQ_INT(1, sdr_rcv_array_get_beam(rcv, rcv->nrfch, &az, &el));
    TEST_ASSERT_NEAR(0.25, az, 1e-12);
    TEST_ASSERT_NEAR(0.75, el, 1e-12);
    TEST_ASSERT_EQ_INT(0, sdr_rcv_array_set_beam(rcv, rcv->nrfch + rcv->narch,
        0.0, 0.0));
    sdr_rcv_array_calib(NULL, NULL, 0, NULL, NULL);
    sdr_rcv_array_calib(rcv, NULL, 0, NULL, NULL);
    
    sdr_rcv_free(rcv_no_array);
    sdr_rcv_free(rcv);
    cleanup_files();
}

// main ------------------------------------------------------------------------
int main(void)
{
    cleanup_files();
    TEST_RUN(test_sdr_rcv_new_free_api);
    TEST_RUN(test_sdr_rcv_new_array_api);
    TEST_RUN(test_sdr_rcv_start_stop_api);
    TEST_RUN(test_sdr_rcv_open_close_api);
    TEST_RUN(test_sdr_rcv_multi_str_api);
    TEST_RUN(test_sdr_rcv_str_error_api);
    TEST_RUN(test_sdr_rcv_offline_eof_drain);
    TEST_RUN(test_sdr_rcv_offline_initial_failure);
    TEST_RUN(test_sdr_rcv_offline_no_channels);
    TEST_RUN(test_sdr_rcv_setopt_api);
    TEST_RUN(test_sdr_rcv_status_api);
    TEST_RUN(test_sdr_rcv_rfch_data_api);
    TEST_RUN(test_sdr_rcv_gain_filt_api);
    TEST_RUN(test_sdr_rcv_array_api);
    cleanup_files();
    
    return 0;
}
