all:
	$(MAKE) -C pocket_scan
	$(MAKE) -C pocket_conf
	$(MAKE) -C pocket_dump
	$(MAKE) -C pocket_acq
	$(MAKE) -C pocket_trk
	$(MAKE) -C pocket_snap
	$(MAKE) -C pocket_calib
	$(MAKE) -C pocket_web
	$(MAKE) -C convbin
	$(MAKE) -C str2str
clean:
	$(MAKE) -C pocket_scan clean
	$(MAKE) -C pocket_conf clean
	$(MAKE) -C pocket_dump clean
	$(MAKE) -C pocket_acq clean
	$(MAKE) -C pocket_trk clean
	$(MAKE) -C pocket_snap clean
	$(MAKE) -C pocket_calib clean
	$(MAKE) -C pocket_web clean
	$(MAKE) -C convbin clean
	$(MAKE) -C str2str clean
install:
	$(MAKE) -C pocket_scan install
	$(MAKE) -C pocket_conf install
	$(MAKE) -C pocket_dump install
	$(MAKE) -C pocket_acq install
	$(MAKE) -C pocket_trk install
	$(MAKE) -C pocket_snap install
	$(MAKE) -C pocket_calib install
	$(MAKE) -C pocket_web install
	$(MAKE) -C convbin install
	$(MAKE) -C str2str install
